### ISSUE TITLE
failed to install cuda on ubuntu20.04.3, need expert help

### ISSUE THREAD

**Issue by gaowayne** [ZaidQureshi/bam#41]
**Describe the bug**
failed to install cuda, our kernel is ubuntu20.04.3, kernel version is 5.8

```
root@salab-hpedl380g11-01:~/wayne/cuda# apt-get install cuda-toolkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libnvidia-decode-560 : Depends: libnvidia-compute-560 (= 560.35.03-0ubuntu1) but 560.35.03-0ubuntu0~gpu20.04.4 is to be installed
 nvidia-driver-560-open : Depends: libnvidia-compute-560 (= 560.35.03-0ubuntu1) but 560.35.03-0ubuntu0~gpu20.04.4 is to be installed
                          Recommends: libnvidia-compute-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-decode-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-encode-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-fbc1-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-gl-560:i386 (= 560.35.03-0ubuntu1)
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@salab-hpedl380g11-01:~/wayne/cuda# apt-get --fix-broken install cuda-toolkit
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libnvidia-decode-560 : Depends: libnvidia-compute-560 (= 560.35.03-0ubuntu1) but 560.35.03-0ubuntu0~gpu20.04.4 is to be installed
 nvidia-driver-560-open : Depends: libnvidia-compute-560 (= 560.35.03-0ubuntu1) but 560.35.03-0ubuntu0~gpu20.04.4 is to be installed
                          Recommends: libnvidia-compute-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-decode-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-encode-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-fbc1-560:i386 (= 560.35.03-0ubuntu1)
                          Recommends: libnvidia-gl-560:i386 (= 560.35.03-0ubuntu1)
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@salab-hpedl380g11-01:~/wayne/cuda# 
```
**To Reproduce**
1. install ubuntu20.04.3 OS, 
2. make sure kernel is 5.8
3. install kernel driver, it works infe
4. try to install cuda driver then build GIDS code
5. see above failure
**Expected behavior**
we can install cuda well
**Screenshots**

**Machine Setup (please complete the following information):**
 - OS ubuntu20.04.3
 - NVIDIA Driver, CUDA Versions, GPU name
 - NV driver 560.35.03
 - 12.6 trying install
 - GPU is L40s
 - SSD used : any NVMe

**Additional context**
Add any other context about the problem here. Add as many description as possible to help you out faster. This is a system's setup, knowing about the system is critical to understand the problem.

**Comment by gaowayne** [comment]
@msharmavikram hello buddy, after I run --fix-broken, above error is gone. but I suffer the cuda build issue after I build libnvm.
but make benchmark failed
```
[100%] Linking CXX shared library lib/libnvm.so
[100%] Built target libnvm
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# make benchmarks
[ 29%] Built target libnvm
[ 32%] Building NVCC (Device) object benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/vectoradd-benchmark-module_generated_main.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at vectoradd-benchmark-module_generated_main.cu.o.cmake:220 (message):
  Error generating
  /root/wayne/bam/bam/build/benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir//./vectoradd-benchmark-module_generated_main.cu.o


make[3]: *** [benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/build.make:65: benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/vectoradd-benchmark-module_generated_main.cu.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1109: benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:361: CMakeFiles/benchmarks.dir/rule] Error 2
make: *** [Makefile:164: benchmarks] Error 2
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# make benchmarks
[ 29%] Built target libnvm
[ 32%] Building NVCC (Device) object benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/vectoradd-benchmark-module_generated_main.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_80'
CMake Error at vectoradd-benchmark-module_generated_main.cu.o.cmake:220 (message):
  Error generating
  /root/wayne/bam/bam/build/benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir//./vectoradd-benchmark-module_generated_main.cu.o


make[3]: *** [benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/build.make:65: benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/vectoradd-benchmark-module_generated_main.cu.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:1109: benchmarks/vectoradd/CMakeFiles/vectoradd-benchmark-module.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:361: CMakeFiles/benchmarks.dir/rule] Error 2
make: *** [Makefile:164: benchmarks] Error 2
```

**Comment by gaowayne** [comment]
@msharmavikram hello buddy, strange, from nvidia smi, I install cuda 12.6, from nvcc -V, it is 10.1

this is root cause? how can I fix this?
```
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# nvidia-smi
Sat Oct 19 11:11:19 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    Off |   00000000:8A:00.0 Off |                    0 |
| N/A   29C    P8             24W /  350W |      23MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2499      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A      3542      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by gaowayne** [comment]
@msharmavikram buddy, I force use nvcc to 12.6. now it works from my side. I need a little help to understand my 1st two run result data. 

the io size is 64B and 4096B(4K), please see below result. the SSD we are using is one gen5 SSD, its read/write BW is more than 10GB/s

1. GIDS most io size is 64B on nvme? 4K io size is not a real workload in GIDS application user story? 
2. is below 64B data make sense to you, what I need tune to get better result?
3. this making page cache process, it will ingest on HBM+DRAM+libnvme, that is why I can see 3000GB/s BW if I test 4K block size, is this correct?

```
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# sudo ./bin/nvm-block-bench --threads=262144 --blk_size=64 --reqs=100 --pages=262144 --queue_depth=1024  --page_size=512 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=128 --random=false
SQs: 255        CQs: 255        n_qps: 128
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f21c6010000       220020410000
HEREN
Cond1
40000 8 8 8000
Finish Making Page Cache
finished creating cache
0000:8A:00.0
atlaunch kernel
Elapsed Time: 7.86991e+06       Number of Ops: 26214400 Data Size (bytes): 13421772800
Ops/sec: 3.33097e+06    Effective Bandwidth(GB/S): 1.58833
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# sudo ./bin/nvm-block-bench --threads=262144 --blk_size=4096 --reqs=100 --pages=262144 --queue_depth=1024  --page_size=512 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=128 --random=false
SQs: 255        CQs: 255        n_qps: 128
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f0318010000       220020410000
HEREN
Cond1
40000 8 8 8000
Finish Making Page Cache
finished creating cache
0000:8A:00.0
atlaunch kernel
Elapsed Time: 3675.9    Number of Ops: 26214400 Data Size (bytes): 13421772800
Ops/sec: 7.13142e+09    Effective Bandwidth(GB/S): 3400.52
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# 
```

**Comment by msharmavikram** [comment]
OMG! My friend don't mess with installation ecosystem and dependency tracking can be a nightmare. 

A big rule of thumb when installing CUDA and drivers when broken like this. Always start with a clean state. Clean up all cuda and drivers fully such that there are no residuals and then start from scratch. Never over fix. It never works out in your favor in long run! 

Coming to your data. 

1. GIDS and BaM are two different projects. GIDS uses BaM. What you are running is only BaM.  
2. Looks like you didn't run the benchmark.sh script. I recommend running that. 
3. blk_size is different than io_size. blk_size is thread block size of GPU. So it cannot go beyond 64. This is why in your second run, it failed and no error is reported. 
4. What you need to do is change few things in the command. Keep blk_size at 64 but change page_size from 512 to 4096 or any other size for changing the IO granularity. Since your drive supports 256 queues, change the queue size too and see (we never tested 256 but good to try). Also enable random=true. 
5. From your first run it seems like 3.3M IOPs we have hit with 512B access. 

Let me know if you have further questions.

**Comment by gaowayne** [comment]
> * blk_size is different than io_size. blk_size is thread block size of GPU. So it cannot go beyond 64. This is why in your second run, it failed and no error is reported.
> * What you need to do is change few things in the command. Keep blk_size at 64 but change page_size from 512 to 4096 or any other size for changing the IO granularity. Since your drive supports 256 queues, change the queue size too and see (we never tested 256 but good to try). Also enable random=true.

thank you so much, buddy. this is very clear to me now. I tried to run GIDS but cmake failed. could you please also help me on this one https://github.com/jeongminpark417/GIDS/issues/22

**Comment by gaowayne** [comment]
@msharmavikram  yeah, page_size is exactly num block size down to libnvme driver. :)
```
            case 3:
                random_access_kernel<3><<<g_size, b_size>>>(h_pc.pdt.d_ctrls, d_pc, page_size, n_threads, d_req_count, settings.n_ctrls, d_assignment, settings.numReqs, settings.accessType, d_access_assignment);
                break;
```

**Comment by gaowayne** [comment]
@msharmavikram I run the write after creating cache, it did not saturate my gen5 TLC that have almost 10GB/s write BW

```
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# ./bin/nvm-block-bench  --threads=262144 --blk_size=64 --reqs=100 --pages=262144 --queue_depth=1024  --page_size=4096 --num_blks=2097152 --gpu=0 --n_ctrls=1 --num_queues=128 --random=true --ratio=0 --access_type=1
SQs: 255        CQs: 255        n_qps: 128
n_ranges_bits: 6
n_ranges_mask: 63
pages_dma: 0x7f20c2010000       220020410000
HEREN
Cond1
40000 8 1 40000
Finish Making Page Cache
finished creating cache
0000:8A:00.0
atlaunch kernel
Elapsed Time: 1.79488e+07       Number of Ops: 26214400 Data Size (bytes): 107374182400
Ops/sec: 1.46051e+06    Effective Bandwidth(GB/S): 5.57139
root@salab-hpedl380g11-01:~/wayne/bam/bam/build# 

```

**Comment by gaowayne** [comment]
@msharmavikram after struggling fix many issues. now for GIDS, I am stuck at below error. :(

GIDS did not document pytorch, python version as BaM. :(

```
root@salab-hpedl380g11-01:~/wayne/gids/GIDS/evaluation# ./gids_unit_test.sh 
Traceback (most recent call last):
  File "GIDS_unit_test.py", line 16, in <module>
    import GIDS
  File "/usr/local/lib/python3.8/dist-packages/GIDS/__init__.py", line 2, in <module>
    from .GIDS import GIDS
  File "/usr/local/lib/python3.8/dist-packages/GIDS/GIDS.py", line 24, in <module>
    from dgl.distributed import DistGraph
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/__init__.py", line 10, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/usr/local/lib/python3.8/dist-packages/dgl/distributed/dist_graph.py", line 12, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/usr/local/lib/python3.8/dist-packages/dgl/graphbolt/__init__.py", line 81, in <module>
    load_graphbolt()
  File "/usr/local/lib/python3.8/dist-packages/dgl/graphbolt/__init__.py", line 66, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Unable to locate the DGL C++ GraphBolt library at /usr/local/lib/python3.8/dist-packages/dgl/graphbolt/libgraphbolt_pytorch_2.4.1.so. This error typically occurs due to a version mismatch between the installed DGL and the PyTorch version you are currently using. Please ensure that your DGL installation is compatible with your PyTorch version. For more information, refer to the installation guide at https://www.dgl.ai/pages/start.html.
root@salab-hpedl380g11-01:~/wayne/gids/GIDS/evaluation# 
[gids] 0:bash*                                               
```

**Comment by msharmavikram** [comment]
Can we take GIDS related questions in GIDS gitrepo please? 

@jeongminpark417 please fix the issues reported by @gaowayne

**Comment by msharmavikram** [comment]
@gaowayne are sure your drives can hit more than 1.5M IOPs for writes ? I have never seen a drive to do that. 

Let's retry with the below parameter changes: 

num_queues=128 -> 255
threads=262144-> 8 million 
Pages=262144 -> 8 million

**Comment by gaowayne** [comment]
> @gaowayne are sure your drives can hit more than 1.5M IOPs for writes ? I have never seen a drive to do that.
> 
> Let's retry with the below parameter changes:
> 
> num_queues=128 -> 255 threads=262144-> 8 million Pages=262144 -> 8 million

@msharmavikram I mean seq write, random write will have SSD internal GC WAF. seq write will have this much IOPS, to check max capability of SW, we can use seq write to test SW

**Comment by msharmavikram** [comment]
Please share your SSD specification so that i have a much better understanding

**Comment by msharmavikram** [comment]
Closing the ticket given no much activity.
